In [1]:
import numpy as np

## Q1. Basic NumPy Array Operations
Create a 1-D NumPy array with 5 elements and perform addition of 2, multiplication by 3, and division by 2.

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])

print("Original array:", arr_1d)
print("Addition of 2:", arr_1d + 2)
print("Multiplication by 3:", arr_1d * 3)
print("Division by 2:", arr_1d / 2)

Original array: [1 2 3 4 5]
Addition of 2: [3 4 5 6 7]
Multiplication by 3: [ 3  6  9 12 15]
Division by 2: [0.5 1.  1.5 2.  2.5]


## Q2. Basic NumPy Array
(a) Reverse the given array. (b) Find all most-frequent values and their indices in arrays `x` and `y`.

In [3]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
print("Reversed array:", arr[::-1])

def most_frequent_values_and_indices(array):
    values, counts = np.unique(array, return_counts=True)
    max_count = counts.max()
    modes = values[counts == max_count]
    return [(value, np.where(array == value)[0]) for value in modes]

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

for name, array in [("x", x), ("y", y)]:
    print(f"\nArray {name}: {array}")
    for value, indices in most_frequent_values_and_indices(array):
        print(f"Most frequent value: {value}, frequency: {len(indices)}, indices: {indices.tolist()}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]

Array x: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1, frequency: 5, indices: [0, 5, 7, 8, 9]

Array y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value: 1, frequency: 3, indices: [0, 1, 2]
Most frequent value: 3, frequency: 3, indices: [4, 8, 9]


## Q3. Access Elements in a 2-D Array
Access the element in the 1st row and 2nd column, and the element in the 3rd row and 1st column.

In [4]:
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

print(arr_2d)
print("1st row, 2nd column:", arr_2d[0, 1])
print("3rd row, 1st column:", arr_2d[2, 0])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
1st row, 2nd column: 20
3rd row, 1st column: 70


## Q4. NumPy Array Properties and Transpose
Create a 1-D array named `arnav_agarwal` with 25 evenly spaced numbers from 10 to 100. Display its dimensions, shape, number of elements, data type, and memory size. Use `reshape()` to create a column vector and transpose it. Check whether `.T` transposes a 1-D array.

In [5]:
arnav_agarwal = np.linspace(10, 100, 25)

print("Array:", arnav_agarwal)
print("Dimensions:", arnav_agarwal.ndim)
print("Shape:", arnav_agarwal.shape)
print("Total elements:", arnav_agarwal.size)
print("Data type:", arnav_agarwal.dtype)
print("Total bytes:", arnav_agarwal.nbytes)

column_array = arnav_agarwal.reshape(25, 1)
print("\nReshaped column array:")
print(column_array)
print("Transpose using reshape and .T:")
print(column_array.T)

print("\nTranspose of the original 1-D array using .T:")
print(arnav_agarwal.T)
print("Does .T change the 1-D array shape?", arnav_agarwal.T.shape != arnav_agarwal.shape)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200

Reshaped column array:
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using reshape and .T:
[[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Transpose of the original 1-D array using .T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Does .T change t

For a 1-D NumPy array, `.T` does not change its shape. Reshape it into a 2-D array first to obtain a row-to-column or column-to-row transpose.

## Q5. NumPy Array Statistics, Reshape, and Resize
Create a 3 × 4 array named `ucs420_arnav_agarwal`. Calculate its mean, median, maximum, minimum, and unique elements. Reshape it to 4 × 3 and resize it to 2 × 3.

In [6]:
ucs420_arnav_agarwal = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original array:")
print(ucs420_arnav_agarwal)
print("Mean:", np.mean(ucs420_arnav_agarwal))
print("Median:", np.median(ucs420_arnav_agarwal))
print("Maximum:", np.max(ucs420_arnav_agarwal))
print("Minimum:", np.min(ucs420_arnav_agarwal))
print("Unique elements:", np.unique(ucs420_arnav_agarwal))

reshaped_ucs420_arnav_agarwal = ucs420_arnav_agarwal.reshape(4, 3)
print("\nReshaped array (4 × 3):")
print(reshaped_ucs420_arnav_agarwal)

resized_ucs420_arnav_agarwal = np.resize(ucs420_arnav_agarwal, (2, 3))
print("\nResized array (2 × 3):")
print(resized_ucs420_arnav_agarwal)

Original array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped array (4 × 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array (2 × 3):
[[10 20 30]
 [40 50 60]]
